#!/usr/bin/env ruby

require_relative 'image_result'
require 'mini_magick'
require 'parallel'
require 'shellwords'
require 'terminal-table'

if ARGV.empty?
  puts "Usage: #{$PROGRAM_NAME} <image_file(s)>"
  Process.exit(-1)
end

ARGV.each do |item|
  basename = File.basename(item)
  item = File.realpath(item)
  result = []
  original_image = ImageResult.new(item, 'ORIGINAL')
  result << original_image

  Dir.mktmpdir("jpegify-#{basename}") do |tmpdir|
    opts = { progress: 'Converting dat JPEG, please wait...' }
    crunch_result = Parallel.map(100.downto(1), opts) do |quality|
      new_path = File.join(tmpdir, "#{basename}-#{quality}.jpg")
      MiniMagick::Tool::Convert.new do |conv|
        conv.quality quality
        conv << item
        conv << new_path
      end
      ImageResult.new(new_path, quality, item)
    end

    result.concat crunch_result
    table = Terminal::Table.new do |t|
      t << ['Quality', 'Filesize', 'Filesize reduction']
      t << :separator
      result.each do |image|
        t << [image.quality, image.human_filesize, image.percent_size_reduction]
      end
    end
    puts table

    open_cmd = Shellwords.join(['xdg-open', tmpdir])
    `#{open_cmd}`
    puts 'Press any key to continue...'
    STDIN.gets.chomp
  end
end
